import "./globals.css";
import { Raleway } from "next/font/google";
import Client from "@/components/clients";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/Footer";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <Navbar />
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
